### PR TITLE
TRIVIAGEN-5: Defining the package structure for core and feature

### PR DESCRIPTION
**Pull request by sidcgithub**
Defines the package structure for core and feature packages

### CODE REVIEW

**Review by Kazoroo — COMMENTED** [review]
What's the difference between core and feature/trivia packages? Also, I think feature package is useless and core, ui, feature1, feature2... can be stored in one folder. Lastly, our app have only one feature yet, right? I mean that user enter topic, AI provides question, then final screen and main menu. It is the core, so you can leave one package called core and create another packages when we want to implement the auth, profile, multiplayer etc.

**Comment by sidcgithub** [comment]
> What's the difference between core and feature/trivia packages? Also, I think feature package is useless and core, ui, feature1, feature2... can be stored in one folder. Lastly, our app have only one feature yet, right? I mean that user enter topic, AI provides question, then final screen and main menu. It is the core, so you can leave one package called core and create another packages when we want to implement the auth, profile, multiplayer etc.

So my intention with core is anything that is shared across different features. For instance it could be used at the launch of the app to see if user already exists and could also be used in user profile feature. 

core can also have base network like retrofit that can be used across the different data layers of different features.

feature package is to organize all the features like login, register, trivia, profile, trivia-result and so on. It gives a clear partition between core and the other features. 

This is a hybrid between Phillip's approach (I don't think he had a features package) and nowinandroid (it has features module) -> [Image](https://github.com/android/nowinandroid/blob/main/docs/images/modularization-graph.drawio.png) 
I think we'll be using the core shortly once we have a baseurl for Retrofit.

**Comment by sidcgithub** [comment]
> What's the difference between core and feature/trivia packages? Also, I think feature package is useless and core, ui, feature1, feature2... can be stored in one folder. Lastly, our app have only one feature yet, right? I mean that user enter topic, AI provides question, then final screen and main menu. It is the core, so you can leave one package called core and create another packages when we want to implement the auth, profile, multiplayer etc.

Are you suggesting something like:
- core
- trivia
- ui
- MainActivity.kt
- TriviaGenApplication.kt

The pros to this approach are simplicity and less overhead. We can introduce features package later if there are more that we create. Also, core would still be handy to include retrofit and can be used for shared functionality. Let me know if this works and I can make the changes.

**Comment by Kazoroo** [comment]
Okey, your suggestion is good, but I would add di package for dependency injection. Everything else is good.

**Comment by sidcgithub** [comment]
Closing the PR. This has been resolved in https://github.com/sidcgithub/ai-trivia-app-android/pull/10

**Pull request closed without merging**
